# Generated by Django 2.2.10 on 2020-10-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0037_auto_20200407_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='caza',
            field=models.CharField(blank=True, choices=[('Beirut', 'Beirut'), ('Bekaa', 'Bekaa'), ('Baalbek-Hermel', 'Baalbek-Hermel'), ('Akkar', 'Akkar'), ('North', 'North'), ('South', 'South'), ('Mont-Lebanon', 'Mont-Lebanon'), ('Nabatiye', 'Nabatiye')], max_length=100, null=True, verbose_name='Caza'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=3, choices=[(1, 'NEEDS ACTION IMMEDIATELY'), (2, 'CAN WAIT 1 DAY'), (3, 'CAN WAIT 2 DAYS')], default=3, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='report_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Complaint on the proper implementation of the COVID-19 preventive measures by the vaccinators', 'Complaint on the proper implementation of the COVID-19 preventive measures by the vaccinators'), ('Complaint on the crowd management at sites', 'Complaint on the crowd management at sites'), ('Complaint on the proper implementation of the preventive measures to protect children being vaccinated', 'Complaint on the proper implementation of the preventive measures to protect children being vaccinated'), ('Complaint on vaccine storage, provision and disposal', 'Complaint on vaccine storage, provision and disposal'), ('Complaint on vaccinator s visibility (ID & brand)', "Complaint on vaccinator's visibility (ID & brand)"), ('Complaint on vaccinator s skills (e.g. technical, interpersonal communication, appearance and cleanliness)', "Complaint on vaccinator's skills (e.g. technical, interpersonal communication, appearance and cleanliness)"), ('Complaint on proper and timely preparation of the community before vaccination', 'Complaint on proper and timely preparation of the community before vaccination'), ('Report on Refusal of vaccination by a community or an institution', 'Report on Refusal of vaccination by a community or an institution'), ('Misconceptions and rumors', 'Misconceptions and rumors'), ('Other challenges or complaints', 'Other challenges or complaints')], max_length=1500, null=True, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sub_report_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Medical reasons ', 'Medical reasons'), ('No trust in the vaccine provided ', 'No trust in the vaccine provided'), ('No trust in the team providing the vaccines', 'No trust in the team providing the vaccines'), ('No trust in the government leading this campaign', 'No trust in the government leading this campaign'), ('Child already vaccinated', 'Child already vaccinated'), ('Based on the recommendation of the pediatric/ physician', 'Based on the recommendation of the pediatric/ physician'), ('Religious reasons', 'Religious reasons'), ('Risk of contracting COVID-19', 'Risk of contracting COVID-19'), ('Anti- vaccination movement ', 'Anti- vaccination movement'), ('Other/ specify', 'Other/ specify')], max_length=1500, null=True, verbose_name='Please specify reasons n the narrative as per the following'),
        ),
    ]
